spring:
  cloud:
    gateway:
      routes:
      - id: after_route #定义第一种路由规则
        uri: http://example.org # 满足predicates指定的所有条件以后就来到uri指定的地方
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
          - 过滤器的名=值

          - StripPrefix=2 #简单过滤器
          - name: Retry #过滤器名
            args: #过滤器定制的参数值
              retries: 3 #
              statuses: BAD_GATEWAY


